### PR TITLE
Fix for BusBreakerConnection creation with a switch connected on a empty bus

### PR DESCRIPTION
**Pull request by SlimaneAmar**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Bug fix

**What is the current behavior?** *(You can also link to an open issue here)*
BusBreakerConnection not created with a switch connected on a empty bus

**What is the new behavior (if this is a feature change)?**
BusBreakerConnection  created with a switch connected on a empty bus

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*
No

### CODE REVIEW

**Comment by floriand-e2r** [comment]
@BenoitJeanson as I don't really get the purpose of removing the fictitious nodes mirroring Bus Nodes, I'm asking for your expertise! if the fictitious nodes mirroring Bus Nodes is a BusBreakerConnection we're losing that connection, as it is removed and subsequently replaced by a fictitious disconnector and fictitious node. As in the changed test case whose result before/after the change is displayed below:
mirroring_before mirroring-after

**Comment by BenoitJeanson** [comment]
This is an old story. I hope I am right. But I remember that in one European  file, each bus (I don't remember if it was of all the substations)  was connected to only one single FictitiousNode which all the cells were connected to.
This ficticiousNode was really just a mirror of the whole busbar. With only externCells, the cellDetector would identify one single megacell per section.

**Comment by floriand-e2r** [comment]
Thx Benoît, I'll try to find that European file for reference! Adding a unit test similar to that file would help in any case, I'll try to do that; it should be in bus breaker view to have both busbreaker connections and that problem.

**Comment by floriand-e2r** [comment]
It seems that 
- the busbreaker connection component introduced in PR #159 
- the fictitious disconnector created if a cell is directly connected to a bus

are two solutions for a same problem, and they collide here. I'll look into how we can combine them.

**Comment by flo-dup** [comment]
BusBreakerConnection was in conflict with fictitious disconnectors, and was therefore removed in PR #241. No need to fix this anymore.

**Pull request closed without merging**
