### PR TITLE
Space for feeder arrows

### PR DESCRIPTION
**Pull request by floriand-e2r**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Yes, #179

### CODE REVIEW

**Comment by floriand-e2r** [comment]
A short explanation of what is done:
- Like suggested in the issue, I added a minSpaceForFeederArrows parameter in LayoutParameters, default equal to 50 (5 times the default arrow size)
- I couldn't use LegBlock to deal with Feeders like suggested: indeed, Feeders are not in LegBlocks as it is so far only for blocks connected to the bus. So, I've dealt with Feeders by not counting them in the V-span calculation of BodyPrimaryBlock and setting the Y coordinate of the feeder node from the root node and not in `BodyPrimaryBlock.coordVerticalCase()`.
- As arrowDistance parameter might not be compatible with arrow size and minSpaceForFeederArrows parameter, the two arrows are centered in the available space when inserting them in the svg if there is less than (2 * arrowDistance + 2 * arrow height)

At the end I think that what I've done with this feeder special care inside BodyPrimaryBlock is similar to what is done with LegPrimaryBlock. Maybe it would be neater to include feeders in LegPrimaryBlock, or in a new Block type, to better fit in the model. What do you think @BenoitJeanson?

**Comment by floriand-e2r** [comment]
Two examples to see before / after
arrow-before_2 arrow-after_2 
arrows-before arrows-after

**Comment by BenoitJeanson** [comment]
The code looks very good: that's cool that you refactor the adaptCellHeight in the meantime. The result is pretty.

**Comment by floriand-e2r** [comment]
Some before/after examples (from test files):
shunt
shunt_aligned
3WT_alignment

**Comment by floriand-e2r** [comment]
I checked the results in all test reference files which I needed to update, but in 3 test reference files there are some changes I don't completely understand. They are in the force-layout package which is using ForceAtlas to display substation diagrams. It seems ok to my understanding but I don't know if I'm right... could you tell me if you think it's ok @FranckLecuyer? as you were the one coding that part. I put here the svg files corresponding to the old json reference vs the ones corresponding to the new json reference:
- ForceLayout Compaction Horizontal
forceLayoutHorizontal
- ForceLayout Compaction Vertical
forceLayoutVertical
- ForceLayout Compaction None
forceLayoutNone

**Comment by geofjamg** [comment]
> I checked the results in all test reference files which I needed to update, but in 3 test reference files there are some changes I don't completely understand. They are in the force-layout package which is using ForceAtlas to display substation diagrams. It seems ok to my understanding but I don't know if I'm right... could you tell me if you think it's ok @FranckLecuyer? as you were the one coding that part. I put here the svg files corresponding to the old json reference vs the ones corresponding to the new json reference:
> 
>     * ForceLayout Compaction Horizontal
>       forceLayoutHorizontal
> 
>     * ForceLayout Compaction Vertical
>       forceLayoutVertical
> 
>     * ForceLayout Compaction None
>       forceLayoutNone

Result does not seem to be worst that with previous code just different, but it is not clear to me why by just changing some margins in the diagram, we end up with voltage level in a totally different order...
@FranckLecuyer any idea?

**Comment by FranckLecuyer** [comment]
> > I checked the results in all test reference files which I needed to update, but in 3 test reference files there are some changes I don't completely understand. They are in the force-layout package which is using ForceAtlas to display substation diagrams. It seems ok to my understanding but I don't know if I'm right... could you tell me if you think it's ok @FranckLecuyer? as you were the one coding that part. I put here the svg files corresponding to the old json reference vs the ones corresponding to the new json reference:
> > ```
> > * ForceLayout Compaction Horizontal
> >   forceLayoutHorizontal
> > 
> > * ForceLayout Compaction Vertical
> >   forceLayoutVertical
> > 
> > * ForceLayout Compaction None
> >   forceLayoutNone
> > ```
> 
> Result does not seem to be worst that with previous code just different, but it is not clear to me why by just changing some margins in the diagram, we end up with voltage level in a totally different order...
> @FranckLecuyer any idea?

In the ForceLayout, the voltage levels are initially added with random positions to the undirected graph used by the ForceAtlas algorithm (see ForceSubstationLayout.java, 'run' method).
So, the voltage levels are not always in the same order in the final svg.

**Review by FranckLecuyer — APPROVED** [review]

**Review by BenoitJeanson — APPROVED** [review]

**Pull request merged**
