### PR TITLE
Improves cgmes dl diagram

### PR DESCRIPTION
**Pull request by CBiasuzzi**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

#5

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

**Comment by CBiasuzzi** [comment]
wrt issue #5, same case - "simple" network, the generated diagram is:

simple

**Comment by geofjamg** [comment]
> wrt issue #5, same case - "simple" network, the generated diagram is:

Nice result, however how do you explain the difference with original diagram especially the x shifting of voltage levels compare to original one where everything is vertically aligned? Same question for wires intermediate points?

**Comment by CBiasuzzi** [comment]
Sorry ... I loaded the exported network + DL into the substation viewer, set the voltage level layout setting to **CGMES** but I left the substation layout setting to **Horizontal**. 
Here below is a rendering with both voltage level and substation layout set to CGMES

simple_2

**Comment by jonenst** [comment]
I can't get this to work after following the steps in #5 to generate a sample_DL.xml and adding it to the sample.zip and then opening that vith network-viewer-app

Tested on 420df4bdac5
Is it just me or does it fail for everyone ?

**Comment by CBiasuzzi** [comment]
A small change to the steps mentioned in #5 is needed:  the exporter's 2nd parameter, in the following code (ref. also the LayoutToCgmesDlExporterTool).
There's a side effect: all the CGMES profiles files are exported, but  you can still pick the single generated DL file and add it to the original sample.zip (same as before) . You can just use all the exported files, of course ...


```
Network network = Importers.loadNetwork("sample.zip");

new LayoutToCgmesExtensionsConverter(new VerticalSubstationLayoutFactory(), new PositionVoltageLevelLayoutFactory(new PositionFree()), new LayoutParameters(), true)
    .convertLayout(network);

new CgmesDLExporter(network, CgmesDLUtils.getTripleStore(network))
    .exportDLData(new FileDataSource(Paths.get("/tmp"), "sample"));

```

**Pull request merged**
