### PR TITLE
Node decorators

### PR DESCRIPTION
**Pull request by floriand-e2r**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Issue #15 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature

**What is the current behavior?** *(You can also link to an open issue here)*
Issue #15 

**What is the new behavior (if this is a feature change)?**
Nodes can be decorated with an image

**Does this PR introduce a breaking change or deprecate an API?** yes 
*If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

**Comment by geofjamg** [comment]
@floriand-e2r when it is ready to final review, you have to remove the draft status and the WIP

**Comment by floriand-e2r** [comment]
Currently the node decorator position expected is relative to the upper left position of the node image. This was done to have the same behaviour as the label position. But I'm wondering if it really makes sense: one might expect a position relative to the center of the node image. This will need to be documented in any case - also for the label position.

**Comment by geofjamg** [comment]
Indeed that would be better to be relative to center. That would be a breaking change to change this behaviour but maybe we should consider it?

**Comment by floriand-e2r** [comment]
I do agree. For the node decorators, this can be done in the current PR. For the labels, I can create a breaking change PR.

**Pull request merged**
